# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make dep
    - make gogenerate
env_files:
  # TODO(jaredallard): likely shouldn't store a git token at a work path
  # but I do this anyways
  github_token: '~/.outreach/github.token'
builds:
- main: ./cmd/bootstraper/bootstraper.go
  id: &name bootstraper
  binary: *name
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
   - '-w -s -X "github.com/tritonmedia/pkg/app.Version={{ .Version }}"'
  env:
  - CGO_ENABLED=0
archives: []
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^(docs|test|build|chore)(\(.+?\))?:'
release:
  github:
    owner: tritonmedia
    name: bootstraper
